name: CI/CD Pipeline - Payment Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    uses: my-banking-app/ci-templates/.github/workflows/java-ms-ci-cd.yml@v1.0.3
    with:
      service-name: "Payment Service"
      docker-image-name: "payment-service"
      service-port: "8085"
      sonar-project-key: "my-banking-app_bank-ms-payment-service"
      java-version: "21"
      maven-command: "mvn clean verify"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}